### ISSUE TITLE
Use consistent version numbers in names

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/module-laravel#9]
From https://github.com/Codeception/module-laravel5/pull/11#issuecomment-751370944 I'm assuming that https://github.com/Codeception/module-laravel5 is dead.
* If this is the case, there should be a big note on https://github.com/Codeception/module-laravel5/blob/master/readme.md
* If not, the repo should be mentioned (i.e. linked at) on https://codeception.com/docs/modules/Laravel5

And https://github.com/Codeception/module-laravel is now the source of https://codeception.com/docs/modules/Laravel5 ? Then the version number should be removed from the docs page, and from the filename https://github.com/Codeception/module-laravel/blob/main/src/Codeception/Module/Laravel5.php

Or am I on the wrong track here?

**Comment by Naktibalda** [comment]
Website hasn't been updated yet.

**Comment by TavoNiievez** [comment]
@ThomasLandauer it seems that you write issues faster than I write code 😄 .

Thanks for your suggestion, I was just working on that when you opened this issue, if you have any other ideas or suggestions for the next version `2.0` this is the time.

**Comment by ThomasLandauer** [comment]
I don't use Laravel, so don't expect any real input from me here ;-)

The note on https://github.com/Codeception/module-laravel5/blob/master/readme.md is still missing, right?

**Comment by TavoNiievez** [comment]
@ThomasLandauer

The repository will be deprecated when version 2 is ready.

So far no upgrades are being made to version 1.x and users should not be notified about the migration for now. Only when a better alternative is ready.

You can send a PR adding the note if you want to go ahead and help. It will be merged the day version 2 is released if you do so.
